apiVersion: v1
kind: Service
metadata: { name: mongo, namespace: lab }
spec:
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
---
apiVersion: apps/v1
kind: StatefulSet
metadata: { name: mongo, namespace: lab }
spec:
  serviceName: mongo
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          args: ["--wiredTigerCacheSizeGB", "0.25"]   # giới hạn RAM cho node nhỏ
          ports: [{ containerPort: 27017 }]
          env:
            - { name: MONGO_INITDB_ROOT_USERNAME, value: root }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: db-secrets, key: MONGO_PASSWORD } }
          resources:
            requests: { cpu: 100m, memory: 384Mi }
            limits: { memory: 768Mi }
          volumeMounts:
            - { name: data, mountPath: /data/db }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: managed-csi
        resources: { requests: { storage: 4Gi } }
